### ISSUE TITLE
Add LRO WAC to ALE and USGSCSM

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#137]
- [x] ALE support
- [x] USGSCSM support

**Comment by jessemapel** [comment]
Initial ISIS processing utility added in https://github.com/USGS-Astrogeology/ISIS3/pull/4936

Initial ALE driver added in https://github.com/USGS-Astrogeology/ale/pull/447

Initial PF added to USGSCSM in https://github.com/USGS-Astrogeology/usgscsm/pull/374

There were also various additional PRs tweaking functionality.
