### ISSUE TITLE
EIS Image Ingestion

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#181]
Finalize ingestion of EIS images from PDS4 to ISIS based on SIS and/or sample labels. 

- [ ] NAC Framing
- [ ] NAC Rolling Shutter
- [ ] WAC Framing
- [ ] WAC Rolling Shutter

**Comment by jessemapel** [comment]
Completed in https://github.com/USGS-Astrogeology/ISIS3/pull/4965
