### ISSUE TITLE
SPICE Kernel Documentation

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#29]
Task Description: Published documentation describing which active flight missions have SPICE kernels that are automatically updated and the update cadence

**Comment by kberryUSGS** [comment]
This work is documented here: https://github.com/USGS-Astrogeology/ISIS3/wiki/Spice-Kernel-Updates-in-ISIS
There are still some "unknowns" listed in the mission release schedule categories that need to be filled in, so this is not yet done.

**Comment by ladoramkershner** [comment]
The table has been updated with information from the NAIF / missions teams. The only information that is still 'Unknown' is the Juno kernel updates. Some kernel information (like Dawn and MEX) may need to be updated later in FY22.
