### ISSUE TITLE
Deploy Docs to Search Engine Indexed Solution

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#32]
Task Description: Publish documentation to a solution indexed by Google and other major search engines to ensure high visibility of ASC documentation

**Comment by ladoramkershner** [comment]
As part of the FY21 Documentation task we are integrating the Sphinx documentation engine and subsequently connecting the built docs to ReadtheDocs (RTD) for the following ASC projects:
- ale
- plio
- usgscsm
- AutoCNet
- knoten
- (stretch) ISIS (developer documentation only)

RTD is able to be indexed by Google. This work has thus far not altered:
- ISIS (application documentation; however it is already on a Google-indexable solution)
- PyHAT (not slated)
- plurmy (not slated)
- pysis (not slated)
- pfeffernusse (not slated)

**Comment by ladoramkershner** [comment]
ale RTD page: https://ale.readthedocs.io/en/latest/
plio RTD page: https://plio.readthedocs.io/en/latest/
usgscsm RTD page: https://usgscsm.readthedocs.io/en/latest/
knoten RTD page: https://knoten.readthedocs.io/en/latest/

doc pages to come by end of FY21: AutoCnet and ISIS dev

**Comment by ladoramkershner** [comment]
I am closing because all baseline goals were met with deploying ASC project documentation on Readthedocs, which is a search engine indexed solution. (excluding ISIS dev docs, which was a strech)
