### ISSUE TITLE
Continuous deploy docs

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#33]
Task Description: Modify the build/deploy pipelines to support automatic documentation deploys to keep documentation current

**Comment by ladoramkershner** [comment]
As part of the FY21 Documentation task we are deploying the Sphinx documentation engine and subsequently connecting the built docs to ReadtheDocs (RTD) for the following ASC projects:
- ale
- plio
- usgscsm
- AutoCNet
- knoten
- (stretch) ISIS (developer documentation only)

Automatic documentation building and deployment is handled by RTD and is triggered after every github PR. This work has thus far not included:
- ISIS (application documentation; slated for FY22 work)
- PyHAT (not slated)
- plurmy (not slated)
- pysis (not slated)
- pfeffernusse (not slated)

The ISIS application documentation is not currently planned to be automatically deployed. Instead, the plan is to keep the ISIS application documentation on their current site, where the community already knows where to look for them, and create a versioning to correspond with ISIS releases. Then create procedural documentation to update the documentation during the ISIS release process.

**Comment by ladoramkershner** [comment]
Please let me know if I have missed any ASC projects in my attempt at an exhaustive list. Additionally, if the community has expressed interest in versioned documentation, should we not consider this for the other ASC projects?

**Comment by ladoramkershner** [comment]
Relevant PRs associated with this work, per project are:
ALE
- [404](https://github.com/USGS-Astrogeology/ale/pull/404)
- [405](https://github.com/USGS-Astrogeology/ale/pull/405)
- [406](https://github.com/USGS-Astrogeology/ale/pull/406)
- [407](https://github.com/USGS-Astrogeology/ale/pull/407)
- [408](https://github.com/USGS-Astrogeology/ale/pull/408)
- [418](https://github.com/USGS-Astrogeology/ale/pull/418)
- [419](https://github.com/USGS-Astrogeology/ale/pull/419)

ale RTD page: https://ale.readthedocs.io/en/latest/

PLIO
- [159](https://github.com/USGS-Astrogeology/plio/pull/159)

plio RTD page: https://plio.readthedocs.io/en/latest/

USGSCSM
- [332](https://github.com/USGS-Astrogeology/usgscsm/pull/332)

usgscsm RTD page: https://usgscsm.readthedocs.io/en/latest/

AUTOCNET
 - [532](https://github.com/USGS-Astrogeology/autocnet/pull/532) > still open 


KNOTEN
- [86](https://github.com/USGS-Astrogeology/knoten/pull/86)

knoten RTD page: https://knoten.readthedocs.io/en/latest/

**Comment by ladoramkershner** [comment]
We were not able to transition the ISIS developer documentation this year (a stretch goal). But all base goals were accomplished.
