### ISSUE TITLE
(Enhanced) Update other ISIS Apps using direct SPICE calls

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#35]
Task Description: Update any other ISIS applications directly furnishing SPICE kernels to support using the SPICE server

**Comment by kberryUSGS** [comment]
Two additional apps where updated as part of this work. https://github.com/USGS-Astrogeology/ISIS3/issues/4303

(1) [shadow](https://github.com/USGS-Astrogeology/ISIS3/pull/4335)
(2) [hjitreg]()
