### ISSUE TITLE
ISIS Cleanup Spurious Files

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#36]
Task Description: Remove spurious files from the ISIS directory tree that have resulted from architectural changes (e.g., transition to CMake, transition to GTest, etc.)

**Comment by scsides** [comment]
PRs:
https://github.com/USGS-Astrogeology/ISIS3/pull/4295
https://github.com/USGS-Astrogeology/ISIS3/pull/4293
https://github.com/USGS-Astrogeology/ISIS3/pull/4292
