### ISSUE TITLE
PVL/BLOB Exposed via SWIG

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#42]
Task Description: The PVL and BLOB libraries exposed in Python via SWIG (Baseline)

**Comment by jessemapel** [comment]
PVL SWIG complete as of https://github.com/USGS-Astrogeology/ISIS3/commit/646bc92c21b9790cb5142a0b81a78608791e3577

BLOB SWIG in progress still

**Comment by jessemapel** [comment]
Done with https://github.com/USGS-Astrogeology/ISIS3/pull/4613
