### ISSUE TITLE
C++ Kernel Selection Prototype

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#44]
Task Description: C/C++ prototype showing Kernel Selection matching ISIS’s results with a C/C++ interface.

**Comment by Kelvinrr** [comment]
This should be closed by: https://github.com/USGS-Astrogeology/SugarSpice/pull/5

Docs on how it works: https://sugar-spice.readthedocs.io/en/latest/reference/tutorials.html#creating-new-mission-config-files
