### ISSUE TITLE
(Enhanced) Mature C++ Kernel Selection Prototype in Mature Library

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#45]
Task Description: Mature C/C++ prototype into a standalone library (Enhanced)

**Comment by Kelvinrr** [comment]
This one is poorly defined (my bad lol), but I am going to interpret this as being ready to do a 1.0 release by end of fiscal. We are most likely not going to make this enhanced goal as I think there is still some API polish work necessary and additional mission support.
