### ISSUE TITLE
C++ Interface for Text Kernel I/O

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#48]
Task Description: C/C++ interface for reading and writing text kernels

**Comment by Kelvinrr** [comment]
This needs https://github.com/USGS-Astrogeology/SugarSpice/issues/42 to be closed, but should be done as part of end of year wrap up as Stuart is not in the current sprint.

**Comment by Kelvinrr** [comment]
I take that back, closed by https://github.com/USGS-Astrogeology/SugarSpice/pull/65/files, technically, issue USGS-Astrogeology/SugarSpice#42 is now a nice to have.
