### ISSUE TITLE
C++ Interface for Binary Kernel I/O

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#49]
Task Description: C/C++ interface for reading and writing binary kernels

**Comment by Kelvinrr** [comment]
closed by https://github.com/USGS-Astrogeology/SugarSpice/pull/67,  https://github.com/USGS-Astrogeology/SugarSpice/pull/53 and https://github.com/USGS-Astrogeology/SugarSpice/pull/66
