### ISSUE TITLE
Convert Tests

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#52]
Task Description: Translate applications based on the availability of existing fixtures and those with the largest data volumes.

**Comment by Kelvinrr** [comment]
Sprint completed early into the FY. Multiple PRs in to ISIS over the course of a few months. Abstract (https://www.hou.usra.edu/meetings/planetdata2021/pdf/7064.pdf) and Poster (https://www.hou.usra.edu/meetings/planetdata2021/eposter/7064.pdf) submitted to PDW as a summary of work completed.
