### ISSUE TITLE
Documentation and Example: AutoCNet Outlier Measures

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#54]
Task Description: Documentation and an example of how to identify potential outlier control measures using computer vision techniques available in AutoCNet

**Comment by jessemapel** [comment]
Done in the USGS workshop:

https://github.com/USGS-Astrogeology/autocnet/blob/dev/docs/users/workshops/FY21_workshop/3_outlier_detection.ipynb
