### ISSUE TITLE
Data Snooping

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#56]
Task Description: Software that identifies potential outlier control measures using data snooping with a single iteration of bundle adjustment

**Comment by jessemapel** [comment]
Work going on under https://github.com/USGS-Astrogeology/ISIS3/issues/4559

**Comment by jessemapel** [comment]
Done in Knoten https://github.com/USGS-Astrogeology/knoten/pull/76
