### ISSUE TITLE
Presentation of New Control Capabilities

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#57]
Task Description: Presentation of new software capabilities at an appropriate conference

**Comment by jessemapel** [comment]
To be presented at an OpenPlanetary Tuesday talk

**Comment by jessemapel** [comment]
Presentation is done and will be presented October 26th. This has also been presented internally to the APPL group. I'll follow up here with a link to the OpenPlanetary recording once it's done.
