### ISSUE TITLE
Participate in CSM Working Group

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#62]
Task Description: Support and continue to participate with the CSM working group.

**Comment by thareUSGS** [comment]
Supported CSM members in GeoINT telecon. 1 of 3 sessions so far. Listed CSM resources and how planetary sensors are operated and located using SPICE.

**Comment by thareUSGS** [comment]
conference particiapation:

1. Presented CSM/SOCET GXP updates for the Lunar Surface Innovation Consortium (LSIC) Workshop on Lunar Mapping for Precision Landing.  This was a collaborative talk with ASU talking to LROC NAC stereo processing in SOCET SET (M. Manheim). Presentation is hosted here: http://lsic.jhuapl.edu/News-and-Events/Agenda/index.php?id=120
2. On Friday, July 2nd (6 am PDT) at the Planetary Data Workshop, there is a birds-of-a-feather on "Stereo and Topography" where we will present the latest on usgscsm and testing in GXP (and hopefully ASP).

**Comment by jessemapel** [comment]
This is on-going, but I'm going to close it as we've initiated the interactions and they will continue on into the next fiscal.
