### ISSUE TITLE
Conference Presentation on CSM

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#63]
Task Description: Report progress at the 5th Planetary Data Workshop or similar meeting and continue to educate NASA (and instrument teams).

**Comment by thareUSGS** [comment]
conference participation:

Presented CSM/SOCET GXP updates for the Lunar Surface Innovation Consortium (LSIC) Workshop on Lunar Mapping for Precision Landing. This was a collaborative talk with ASU talking to LROC NAC stereo processing in SOCET SET (M. Manheim). Presentation is hosted here: http://lsic.jhuapl.edu/News-and-Events/Agenda/index.php?id=120
On Friday, July 2nd (6 am PDT) at the Planetary Data Workshop, there is a birds-of-a-feather on "Stereo and Topography" where we will present the latest on usgscsm and testing in GXP (and hopefully ASP). https://www.hou.usra.edu/meetings/planetdata2021/pdf/planetdata2021_program.htm#sess501

**Comment by jessemapel** [comment]
We are also similarly working to support specific mission teams with using Socet GXP with USGSCSM/ALE.
