### ISSUE TITLE
PDS4 Templating Libraries

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#65]
Task Description: Research templating libraries (Jinja, Velocity, Mako, and GDAL capabilities) to determine if they meet the requirements

**Comment by scsides** [comment]
The inja templating library was chosen due to it being one of two C++ template libraries. The other library has not been maintained recently.

PRs:
https://github.com/USGS-Astrogeology/ISIS3/pull/4207
