### ISSUE TITLE
(Enhanced) Import PDS4 image

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#71]
Task Description: Using the new system, import a PDS4 image from a currently supported instrument (e.g., Cassini NIMS) into ISIS (Enhanced)

**Comment by scsides** [comment]
PRs:
https://github.com/USGS-Astrogeology/ISIS3/pull/4490
https://github.com/USGS-Astrogeology/ISIS3/pull/4482
https://github.com/USGS-Astrogeology/ISIS3/pull/4478
https://github.com/USGS-Astrogeology/ISIS3/pull/4477
https://github.com/USGS-Astrogeology/ISIS3/pull/4472
https://github.com/USGS-Astrogeology/ISIS3/pull/4470
https://github.com/USGS-Astrogeology/ISIS3/pull/4228
https://github.com/USGS-Astrogeology/ISIS3/pull/4212
https://github.com/USGS-Astrogeology/ISIS3/pull/4505/
