### ISSUE TITLE
AstroLink Web-Based Archive Management System

### ISSUE THREAD

**Issue by mahunterUSGS** [USGS-Astrogeology/softwaremanagement#83]
AstroLink needs to transfer collection inventories stored in Excel spreadsheets into a web-based archive management system with public/private controls. CollectiveAccess has been identified as the candidate platform. Existing inventories are located on the shareall at S:\RPIF\Inventories\Inventories_Working_Astro\Most Recent Inventories (11_2020).

**Comment by Kelvinrr** [comment]
Code available here: https://code.chs.usgs.gov/asc/astrolink and deployed to astrolink.wr.usgs.gov
