### ISSUE TITLE
Terrestrial Analogs Data Portal

### ISSUE THREAD

**Issue by mahunterUSGS** [USGS-Astrogeology/softwaremanagement#84]
Here is the MVP for the Data Portal:
MVP 1) Define geophysical processes and other search criteria (complete)
MVP 2) Define a metadata standard (complete, FGDC and ISO)
MVP 3) Determine workflow for data uploads from the community (not currently allowable under USGS policy)
MVP 4) Determine web platform and considerations (AWS web app - can/should be revisited)
MVP 5) Create a process to ingest ScienceBase data (complete, through the SB interface)
MVP 6) Create basic text and geospatial search functionality (not started, planned to scrape SB items with pre-canned queries from our Terrestrial Analogs community and relevant related searches - can/should be revisited https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Item+Core+Model)
MVP 7) Create a prototype front end interface with basic mapping (React inteface started https://code.chs.usgs.gov/asc/dk8s/terrestrial-analogs)
MVP 8) Write documentation (not started)

**Comment by jlaura** [comment]
@mahunterUSGS Thanks for this. I would love to break this up some into the items that the dev team are going to be working on. It looks like I should generate individual issues for:

- MVP 4) Determine web platform and considerations (AWS web app - can/should be revisited)
- MVP 6) Create basic text and geospatial search functionality (not started, planned to scrape SB items with pre-canned queries from our Terrestrial Analogs community and relevant related searches - can/should be revisited https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Item+Core+Model)
- MVP 7) Create a prototype front end interface with basic mapping (React inteface started https://code.chs.usgs.gov/asc/dk8s/terrestrial-analogs)
MVP 8) Write documentation (not started)

Is that accurate?

**Comment by mahunterUSGS** [comment]
That is accurate, thanks!

**Comment by mahunterUSGS** [comment]
Project MVPs delivered. Will create new issues to clarify documentation needed and wish list of minor updates.
