### ISSUE TITLE
Budget Web Site Improvements

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/softwaremanagement#85]
This is working on the Python migration of the existing budget estimating web tool.  The existing web tool uses Twig, which is a PHP implementation of Jinja.  This has allowed for the presentation layer to be carried forward with very little coding.  The primary goal of this sprint will be to implement the budget reporting interfaces which all rely on a shared dict export from the database. 

Repo link https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site 

Tasks 

- Finish implementation of budget reports (2 developers 60 hours each) 
- The source data dict/hash needs to be created from the database for a given budget.  Rebecca Leggett did research on the fields that the report Jinja templates are expecting https://github.com/USGS-Astrogeology/Astro-Budget-Site/wiki 

The following report interfaces all use this dict to populate their templates: 
- Budget details https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site/-/blob/master/app/templates/proposal-budget-details.html 
- ROSES (or redacted) view https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site/-/blob/master/app/templates/proposal-roses.html 
- NSPIRES view https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site/-/blob/master/app/templates/proposal-nspires.html 
- Editing dashboard AJAX feed (ie. The D3.js graphs at the top of the budget editing page) https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site/-/blob/master/app/templates/proposal-costs-ajax.json 
- Editing titles AJAX feed (for the accordions, this shows a simplified cost breakdown for that section) https://code.chs.usgs.gov/asc/astro-k8s/astro-budget-site/-/blob/master/app/templates/proposal-cost-titles-ajax.json 

- Devops Improvements (2 developers 40 hours each) 
Evin has set up k8s containers that have CI/CD for testing of the dev site.  There may be some tuning and modifying these containers as needed.  We want to have a way for development to be done on local systems as well as the CI/CD to the k8s cluster Evin has already set up.

**Comment by jlaura** [comment]
Closing this issue in favor of individually enumerated issues. Will link back to this issue as appropriate.
